# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBZHuvc0vh3XlMugHy6NyVBiVO-oYa30
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# 1. Chargement
df = pd.read_csv('Dataset_Studelecta_Final_2026.csv')

# 2. Paramètres
pays_europeens = ['BEL', 'DEU', 'ESP', 'FRA', 'GBR', 'ITA', 'LUX']
annees_futures = [2024, 2025, 2026, 2027, 2028]
resultats_liste = []

# 3. Boucle par pays : Analyse + Prédiction Linéaire (pour l'augmentation)
for code in pays_europeens:
    data_pays = df[df['Code_Destination'] == code].copy()

    # --- PARTIE GAUCHE : CORRÉLATION ---
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 5))
    sns.heatmap(data_pays[['Annee', 'Montant_Bourses_MUSD', 'Nombre_Etudiants_Africains']].corr(),
                annot=True, cmap='YlGnBu', fmt=".2f", ax=ax1, cbar=False)
    ax1.set_title(f'Logique de Corrélation : {code}')

    # --- PARTIE DROITE : PRÉDICTION LINÉAIRE (Extrapolation) ---
    model = LinearRegression()
    # On apprend la relation entre l'Année et le Nombre d'étudiants
    model.fit(data_pays[['Annee']], data_pays['Nombre_Etudiants_Africains'])

    # Prédiction pour les 5 années suivantes
    futur_X = pd.DataFrame({'Annee': annees_futures})
    preds_futures = model.predict(futur_X)

    # Stockage pour le classement
    for annee, val in zip(annees_futures, preds_futures):
        resultats_liste.append({
            'Année': annee,
            'Pays': code,
            'Étudiants': int(val)
        })

    # Tracé avec une ligne qui monte
    sns.lineplot(x=annees_futures, y=preds_futures, marker='s', ax=ax2, color='green', linewidth=2)
    for x, y in zip(annees_futures, preds_futures):
        ax2.text(x, y, f'{int(y):,}', ha='center', va='bottom', fontsize=9, fontweight='bold')

    ax2.set_title(f'Projection Studelecta 2024-2028 : {code}')
    ax2.set_xticks(annees_futures)
    plt.tight_layout()
    plt.show()

# 4. CLASSEMENTS ANNUELS (Avec augmentation visible)
df_final = pd.DataFrame(resultats_liste)

print("\n" + "="*60)
print("CLASSEMENTS ANNUELS AVEC PROGRESSION (2024-2028)")
print("="*60)

for annee in annees_futures:
    print(f"\n--- TOP DESTINATIONS {annee} ---")
    top = df_final[df_final['Année'] == annee].sort_values(by='Étudiants', ascending=False)
    top = top.reset_index(drop=True)
    top.index += 1
    print(top[['Pays', 'Étudiants']])